- hosts: zxz
  remote_user: root
  tasks:
    - name: install vshtpd
      yum:
        name: vsftpd
        state: present
    - name: config vshtpd
      template: 
        src=vsftpd.conf 
        dest=/etc/vsftpd/vsftpd.conf
    - name: vsftpd login  
      copy: 
        src=vsftpd 
        dest=/etc/pam.d/vsftpd
      notify: restart vsftpd
    - name: start vsftpd
      service: 
        name: vsftpd
        state: started
    - name: add ftpuser
      user:
        name: "{{item.user}}"
        password: "{{'item.pass'|password_hash('sha512')}}"
        home: /data/gitlab_list/
        shell: /sbin/nologin
        state: present
      #  when: ansible_default_ipv4.address == "192.168.40.239"
      loop: 
         - { user: userA,pass: xxx123 }
        # - { user: userB,pass: xxx013123   }
            
  handlers:
    - name: restart vshtpd
      service:
        name: vsftpd
        state: restarted
